Add an annotations field to the eksctl config file
weaveworks/eksctl pull request #2632
Opened 2020-09-10 05:26 UTC by hikhvar

Issue #2631

### Description

### Checklist
- [ x ] Added tests that cover your change (if possible)
- [ x ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ x ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [ x ] Make sure the title of the PR is a good description that can go into the release notes

2020-09-10 08:49 UTC, michaelbeaumont requested changes

2020-09-10 08:49 UTC, michaelbeaumont commented on pkg/apis/eksctl.io/v1alpha5/types.go
> +	// and can be used by automation tools build by the user
```suggestion
	// Annotations are arbitrary metadata ignored by `eksctl`.
```

2020-09-14 13:11 UTC, michaelbeaumont approved these changes

2020-09-14 14:40 UTC, michaelbeaumont commented
@hikhvar you'll have to rebase/merge and run `make generate-all` again

2020-09-15 05:55 UTC, hikhvar commented
Rebased, squashed and regenerated all files. :crossed_fingers:

2020-09-15 06:57 UTC, merged