post a warning about deprecating static AMI resolver
weaveworks/eksctl pull request #2710
Opened 2020-10-05 20:20 UTC by neha-viswanathan

### Description

This MR contains a warning in the command description of `create nodegroup` to warn about the deprecation of the static AMI resolver.
Related to #2661 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Added labels for change area (e.g. `area/nodegroup`), target version (e.g. `version/0.12.0`) and kind (e.g. `kind/improvement`)
- [x] Make sure the title of the PR is a good description that can go into the release notes

2020-10-05 20:23 UTC, neha-viswanathan commented
@michaelbeaumont @martina-if please review. Thanks!

2020-10-06 08:44 UTC, michaelbeaumont requested changes
I think a warning should be printed when we see the user is using the resolver here:
https://github.com/weaveworks/eksctl/blob/eff895ad956766480fb916de910e49036af15807/pkg/eks/api.go#L277-L278

2020-10-06 08:44 UTC, michaelbeaumont commented on pkg/ctl/create/nodegroup.go
> -	cmd.SetDescription("nodegroup", "Create a nodegroup", "", "ng")
I don't think the warning should be shown here, because it's about a very specific option.

2020-10-06 08:45 UTC, michaelbeaumont commented on pkg/ctl/create/nodegroup.go
> -	cmd.SetDescription("nodegroup", "Create a nodegroup", "", "ng")
Please also mention release `0.33.0` as the deprecation point.

2020-10-07 12:41 UTC, michaelbeaumont approved these changes

2020-10-08 11:20 UTC, cPu1 approved these changes

2020-10-08 11:20 UTC, cPu1 commented on pkg/eks/api.go
> +		logger.Warning("'static' value for node-ami flag is deprecated and will be removed with release 0.33.0. Valid values will be 'auto-ssm' (default), 'auto' or an AMI id (advanced use)")
We should also specify the field name:
```suggestion
		logger.Warning("'static' value for node-ami flag (nodeGroup.ami field) is deprecated and will be removed with release 0.33.0. Valid values will be 'auto-ssm' (default), 'auto' or an AMI id (advanced use)")
```

2020-10-08 12:05 UTC, merged