Add support for dry-run
weaveworks/eksctl pull request #3451
Opened 2021-03-18 19:06 UTC by cPu1

### Description

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2021-03-19 13:36 UTC, aclevername requested changes
Looks good! Two things:
- Just out of curiosity have you tried using the config you get as an output as input to eksctl? It sounds silly but with the way we mutate the config I wouldn't be surprised if some bug exists/gets introduced meaning that it doesn't work. Could potentially be worth an integration test?
- I can see the integration test failing a lot as whenever we add a new field to the cluster/nodegroup struct you need to remember to update this test, which won't get noticed in a github PR as we don't run the integration tests. Could we move this test/copy a portion of this test to live somewhere that ensures it gets run as part of `make test`/PR flow?

2021-03-22 09:24 UTC, aclevername commented
> It is! I was planning to address it in a separate PR, as part of adding an integration test for `create nodegroup`.

sweet!

> We don't run the integration tests for PRs, but we do build the integration tests, so any compilation errors will cause the PR checks to fail.

Its not compilation errors I'm worried about, its PRs like [this](https://github.com/weaveworks/eksctl/pull/2754) that are small so you wouldn't think to run the integration test, but would cause this test to fail as it introduces a new field. I think catching this before its merged would be really useful

2021-03-23 14:42 UTC, cPu1 commented
The dry-run integration test is failing because it needs AWS credentials. I'm working on it.

2021-03-24 14:29 UTC, aclevername commented
> The dry-run integration test is failing because it needs AWS credentials. I'm working on it.

out of curiosity what sort of API calls do we make during dry-run that need creds? VPC validation?

2021-03-25 13:50 UTC, cPu1 commented
>out of curiosity what sort of API calls do we make during dry-run that need creds? VPC validation?

One of the first checks performed by every command is `sts.GetCallerIdentity`, so it's failing on that.

2021-03-25 13:58 UTC, cPu1 commented
Regarding running the dry-run integration test upon pushing to `main`, IMO, it's not worth the effort of introducing a new GH action that runs just the dry-run integration test to ensure any changes to the ClusterConfig schema are caught. I think we just have to accept that it's the same as other integration tests, and if the integration test suite didn't take too long to complete, we could've run it upon pushing to `main`. 

In the future, we can consider writing a custom check that reads the `defaultClusterConfig` variable and compares it with the output of the default ClusterConfig as part of the PR workflow.

2021-03-25 17:06 UTC, aclevername commented on pkg/ctl/create/cluster.go
> +	}
does this stop `logger.Error` calls from output?

2021-03-25 17:06 UTC, aclevername approved these changes
LGTM, just need to update the integration test to create a cluster using the output of the dry run

2021-03-30 14:55 UTC, merged