Update eks-managed-nodes.md
weaveworks/eksctl pull request #3653
Opened 2021-04-30 22:32 UTC by lboix

Adding a tip for the usecase where you are describing your whole EKS cluster in just one single file

### Description

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2021-05-02 06:39 UTC, cPu1 requested changes
Thanks for the PR! I left some minor comments but otherwise LGTM.

2021-05-02 06:39 UTC, cPu1 commented on userdocs/src/usage/eks-managed-nodes.md
> +Tip : if you are using only one *`YOUR_CLUSTER.yaml`* file to describe your whole cluster, describe your new managed node group in its `managedNodeGroups` directive and run\:
I think this is more clear:

```suggestion
Tip : if you are using a `ClusterConfig` file to describe your whole cluster, describe your new managed node group in its `managedNodeGroups` field and run\:
```

2021-05-02 06:39 UTC, cPu1 commented on userdocs/src/usage/eks-managed-nodes.md
> +$ eksctl create nodegroup --config-file=YOUR_CLUSTER.yaml --include='YOUR_MANAGEDNODEGROUP_NAME'
By default, `eksctl create nodegroup` detects non-existing nodegroups and creates them, so `--include` can be omitted. 

```suggestion
$ eksctl create nodegroup --config-file=YOUR_CLUSTER.yaml'
```

2021-05-02 18:28 UTC, lboix commented
> Thanks for the PR! I left some minor comments but otherwise LGTM.

I saw them and validated

> Thanks for the PR! I left some minor comments but otherwise LGTM.

Thanks for your feedback! I saw them and applied them

2021-05-04 07:14 UTC, cPu1 commented on userdocs/src/usage/eks-managed-nodes.md
> +$ eksctl create nodegroup --config-file=YOUR_CLUSTER.yaml'
```suggestion
$ eksctl create nodegroup --config-file=YOUR_CLUSTER.yaml
```

2021-05-05 15:37 UTC, cPu1 approved these changes

2021-05-05 15:38 UTC, merged