Create nodegroups in integration tests with SSM enabled
weaveworks/eksctl pull request #3829
Opened 2021-06-11 08:24 UTC by cPu1

### Description

In a future release, EKS AMIs might include the SSM agent by default. In preparation for that, this changelist adds an env var to enable SSM for all nodegroups, and sets it for integration tests.

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2021-06-11 14:01 UTC, Callisto13 requested changes
I don't think this is something we should give to customers, even if it is not documented. It may be more work, but let's update the integration tests

2021-06-14 11:08 UTC, cPu1 commented
It's a lot more manual work to update the integration tests because both `create cluster` and `create nodegroup` need to be updated to pass `--enable-ssm` and include `ssh.enableSsm` for every nodegroup if a config file is being used. It's possible to miss some tests this way. 

I'm thinking a better alternative is to use an environment variable that clearly signifies it's internal and may be removed in a future release, like `_____INTERNAL_NODEGROUP_ENABLE_SSM`.

2021-06-14 11:22 UTC, Callisto13 commented
I am really against releasing anything which has nothing to do with customers or even eksctl.

There are like 13 test files, and they are not that long. It will take like less than 10 mins to update them all, and if we miss one 🤷‍♀️  we'll find out soon enough. This really isn't something we should be spend more than 30 seconds thinking about

2021-06-15 08:49 UTC, Callisto13 approved these changes

2021-06-15 09:00 UTC, merged