Fix nodegroup get when no nodes are present
weaveworks/eksctl pull request #4928
Opened 2022-03-10 10:52 UTC by vflaux

### Description

We ignore "no nodes were found" errors from `kubewrapper.GetNodegroupKubernetesVersion()` so `get nodegroups` command will not fails in such cases.

fix #4927

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2022-03-10 13:20 UTC, nikimanoledaki requested changes
I left a comment with some thoughts. Please also update the unit tests! :) 
Thanks again for opening a PR to fix this! 🎉

2022-03-10 16:19 UTC, vflaux commented on pkg/kubernetes/nodegroup.go
> +		return "", errors.Wrap(errors.New(NO_NODE_FOUND), "failed to list nodes")
Thanks for the suggestion, it's way simpler this way.
We don't actually need to check for the returned value as `summary.Version` is not initialized at this point and so we won't overwrite anything.

2022-03-11 12:14 UTC, aclevername approved these changes

2022-03-11 12:20 UTC, Himangini approved these changes
🎉

2022-03-11 13:44 UTC, nikimanoledaki approved these changes
Great work!!! Thanks again for opening this PR. 🥳 Let's merge it on Monday so that it makes next week's release!

2022-03-15 08:05 UTC, merged