Do not require overrideBootstrapCommand when ami family is Windows
weaveworks/eksctl pull request #5248
Opened 2022-05-12 12:59 UTC by a2ush

### Description

Currently, when you create windows nodes with custom AMI, you have to describe `overrideBootstrapCommand` in the template[ [code 1]](https://github.com/weaveworks/eksctl/blob/3180a16b7a4549e66cad3683ef0a71d719c259f4/pkg/apis/eksctl.io/v1alpha5/validation.go#L648-L650).
However, eksctl ignores the value of `overrideBootstrapCommand` and configures Userdata for windows nodes automatically [[code 2]](https://github.com/weaveworks/eksctl/blob/3180a16b7a4549e66cad3683ef0a71d719c259f4/pkg/nodebootstrap/windows.go#L33-L81).

I think eksctl should indicate overrideBootstrapCommand is not support in windows nodes because you can misunderstand that created windows nodes are configured with your customize Userdata.

[test]
```
$ cat test.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: test-cluster
  region: ap-northeast-1
  version: "1.21"

nodeGroups:
  - name: windows-test-ng
    ami: ami-111111111111
    amiFamily: WindowsServer2019CoreContainer
    overrideBootstrapCommand: |
       <powershell>
       hello world
       </powershell>

$ ./eksctl create nodegroup -f test.yaml
Error: couldn't create cluster provider from options: overrideBootstrapCommand is not supported for WindowsServer2019CoreContainer nodegroups (path=nodeGroups[0].overrideBootstrapCommand)
```

### Checklist
- [X] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [X] Manually tested
- [X] Made sure the title of the PR is a good description that can go into the release notes
- [X] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2022-05-20 06:49 UTC, Skarlso approved these changes
Oh nice, I didn't know this. :D

2022-05-30 09:10 UTC, cPu1 requested changes

2022-05-30 09:10 UTC, cPu1 commented on pkg/apis/eksctl.io/v1alpha5/validation_test.go
> +		It("should not require overrideBootstrapCommand if ami is set and type is Windows", func() {
```suggestion
		It("should throw an error if overrideBootstrapCommand is set and type is Windows", func() {
```

2022-05-30 09:10 UTC, cPu1 commented on pkg/apis/eksctl.io/v1alpha5/validation.go
> +		}
```suggestion
		if IsWindowsImage(ng.AMIFamily) && ng.OverrideBootstrapCommand != nil {
			return fieldNotSupported("overrideBootstrapCommand")
		}
```

2022-06-02 06:20 UTC, a2ush commented on pkg/apis/eksctl.io/v1alpha5/validation_test.go
> +		It("should not require overrideBootstrapCommand if ami is set and type is Windows", func() {
Thanks comment! I fixed it.

2022-06-02 06:20 UTC, a2ush commented on pkg/apis/eksctl.io/v1alpha5/validation.go
> +		}
Thanks comment! I fixed it.

2022-06-02 07:48 UTC, merged