fix coredns wait when no nodegroups
weaveworks/eksctl pull request #5571
Opened 2022-08-03 16:23 UTC by matti

### Description

Fixes #5570

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2022-08-03 16:40 UTC, cPu1 requested changes
Thanks for the PR. I have left a comment to change the condition to account for nodegroups with zero nodes.

2022-08-03 16:40 UTC, cPu1 commented on pkg/actions/addon/addon.go
> +	if addon.Name == api.CoreDNSAddon && (len(a.clusterConfig.NodeGroups) == 0 && len(a.clusterConfig.ManagedNodeGroups) == 0) {
As noted in the linked [issue](https://github.com/weaveworks/eksctl/issues/5570#issuecomment-1204207831), the condition should be

```suggestion
	if addon.Name == api.CoreDNSAddon && !a.clusterConfig.HasNodes() {
```

2022-08-03 16:45 UTC, matti commented
@cPu1 changed to that now.

2022-08-03 16:52 UTC, cPu1 approved these changes
Thanks for the quick fix!

2022-08-08 17:46 UTC, Himangini approved these changes

2022-08-08 18:03 UTC, merged