Stop using 's' as indicator that a method returns a list
weaveworks/eksctl pull request #5680
Opened 2022-09-07 08:59 UTC by TiberiuGC

### Description

We are having a couple of methods that return either some instance or a list of those instances, which are very similar in name. In fact, the one that returns a list ends in an additional `s` (e.g. `DescribeNodeGroupStack` and `DescribeNodeGroupStacks`). This means that using and testing these functions can get error prone in particular scenarios (please see #5219). We've decided to replace the `s` with `List` for such cases. 

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [ ] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2022-09-07 11:23 UTC, Himangini reviewed
small nits :D

2022-09-07 11:23 UTC, Himangini commented on pkg/cfn/manager/nodegroup.go
>  // DescribeNodeGroupStacks calls DescribeStacks and filters out nodegroups
```suggestion
// DescribeNodeGroupStackList calls DescribeStackList and filters out nodegroups
```
💡

2022-09-07 11:23 UTC, Himangini commented on pkg/cfn/manager/cluster.go
>  // DescribeClusterStack calls DescribeStacks and filters out cluster stack
```suggestion
// DescribeClusterStack calls DescribeStackList and filters out cluster stack
```

2022-09-07 11:23 UTC, Himangini commented on pkg/cfn/manager/api.go
>  // DescribeStacks describes the existing stacks
```suggestion
// DescribeStackList describes the existing stacks
```

2022-09-08 11:28 UTC, Himangini approved these changes
LGTM 👍🏻

2022-09-20 17:39 UTC, Himangini approved these changes
👍🏻

2022-09-26 11:27 UTC, cPu1 requested changes
`DescribeStackList` does not read well and implies that `StackList` is the resource that needs to be described, but there is no such resource. `ListStacks` is more descriptive IMO, but there's already a method by that name so we should rename the existing `ListStacks` method to something else, e.g., `ListStacksWithStatuses`.

2022-09-26 15:03 UTC, cPu1 commented on pkg/ctl/cmdutils/filter/nodegroup_filter.go
> +//
Redundant line.

2022-09-26 15:03 UTC, cPu1 approved these changes

2022-09-26 15:43 UTC, merged