fix: support karpenter version > 0.19.x
weaveworks/eksctl pull request #5934
Opened 2022-11-16 05:56 UTC by solidnerd

### Description

During the release of karpenter 0.19.x there were breaking change in the configuration

https://github.com/aws/karpenter/commit/0b122ce5d3b03289300be596163a895994c01713

To support all version mappings it check for the version of karpenter release to install

### Checklist
- [ ] Added tests that cover your change (if possible)
- [ ] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

2022-11-16 12:47 UTC, mbevc1 approved these changes

2022-11-28 17:40 UTC, Himangini requested changes
Please add tests to cover your changes, also see comments below.

2022-11-28 17:40 UTC, Himangini commented on pkg/karpenter/karpenter.go
> +
Please use a version library to compare versions.

2022-11-28 17:40 UTC, Himangini commented on pkg/karpenter/karpenter.go
> +		values = map[string]interface{}{
shouldn't lines 78 to 85 be part of this if's else?

2023-01-04 01:58 UTC, closed without merging

2023-01-04 09:51 UTC, mbevc1 commented
We should probably bump it to 0.21.x